version: '3.3'

services:
  web:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=ossn
      - DB_DB=ossn
      - SITE_PROTOCOL=http
      - SITE_DOMAIN=local.ossn.com
      - SITE_USERDATA=/var/www/ossn_data/
    env_file:
      - local.env
    volumes:
      - ./volumes/ossn:/var/www/html
      - ./volumes/ossn_data:/var/www/ossn_data
      - ./etc/apache/site.conf:/etc/apache2/sites-enabled/local.ossn.com
      - ./etc/entrypoint.sh:/entrypoint.sh
    links:
      - db
    networks:
      - web
      - backend
    entrypoint: /entrypoint.sh
    extra_hosts:
      - "local.ossn.com:127.0.0.1"
    labels:
      - 'traefik.backend=ossn_1'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:local.ossn.com'
      - 'traefik.docker.network=traefik'

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=ossn
      - MYSQL_DATABASE=ossn
      - MYSQL_USER=ossn
      - MYSQL_PASSWORD=ossn
    volumes:
      - db:/var/lib/mysql
      - ./etc/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - backend
    labels:
      - 'traefik.enable=false'

volumes:
  db:

networks:
  web:
    external:
      name: traefik
  backend:
